# Generated by Django 5.2.8 on 2025-12-01 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Title')),
                ('members', models.ManyToManyField(blank=True, related_name='member_of_projects', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
