# Generated by Django 5.2.8 on 2025-12-05 01:22

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')])),
                ('status', models.CharField(blank=True, choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO_DO')),
                ('deadline', models.DateTimeField(blank=True, null=True, validators=[tasks.models.deadline_cant_be_in_past_validator])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_tasks', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_of_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
