# Generated by Django 5.2.8 on 2025-12-07 02:14

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4, verbose_name='Priority')),
                ('status', models.CharField(blank=True, choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO_DO', verbose_name='Status')),
                ('deadline', models.DateTimeField(blank=True, null=True, validators=[tasks.models.deadline_cant_be_in_past_validator], verbose_name='Deadline')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_of_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Executor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sections.section', verbose_name='Section')),
            ],
        ),
    ]
