# Generated by Django 5.2.8 on 2025-12-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4, verbose_name='Priority'),
        ),
    ]
